(cl:defpackage laser_tag-srv
  (:use )
  (:export
   "TAGACTIONOBS"
   "<TAGACTIONOBS-REQUEST>"
   "TAGACTIONOBS-REQUEST"
   "<TAGACTIONOBS-RESPONSE>"
   "TAGACTIONOBS-RESPONSE"
   "YOUBOTACTIONOBS"
   "<YOUBOTACTIONOBS-REQUEST>"
   "YOUBOTACTIONOBS-REQUEST"
   "<YOUBOTACTIONOBS-RESPONSE>"
   "YOUBOTACTIONOBS-RESPONSE"
  ))

