// Generated by gencpp from file laser_tag/TagActionObsRequest.msg
// DO NOT EDIT!


#ifndef LASER_TAG_MESSAGE_TAGACTIONOBSREQUEST_H
#define LASER_TAG_MESSAGE_TAGACTIONOBSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_tag
{
template <class ContainerAllocator>
struct TagActionObsRequest_
{
  typedef TagActionObsRequest_<ContainerAllocator> Type;

  TagActionObsRequest_()
    : action(0)  {
    }
  TagActionObsRequest_(const ContainerAllocator& _alloc)
    : action(0)  {
  (void)_alloc;
    }



   typedef int32_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::laser_tag::TagActionObsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_tag::TagActionObsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TagActionObsRequest_

typedef ::laser_tag::TagActionObsRequest_<std::allocator<void> > TagActionObsRequest;

typedef boost::shared_ptr< ::laser_tag::TagActionObsRequest > TagActionObsRequestPtr;
typedef boost::shared_ptr< ::laser_tag::TagActionObsRequest const> TagActionObsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_tag::TagActionObsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laser_tag::TagActionObsRequest_<ContainerAllocator1> & lhs, const ::laser_tag::TagActionObsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laser_tag::TagActionObsRequest_<ContainerAllocator1> & lhs, const ::laser_tag::TagActionObsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laser_tag

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_tag::TagActionObsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_tag::TagActionObsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_tag::TagActionObsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b028501ac85c840a01d50342b4cc9b6e";
  }

  static const char* value(const ::laser_tag::TagActionObsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb028501ac85c840aULL;
  static const uint64_t static_value2 = 0x01d50342b4cc9b6eULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_tag/TagActionObsRequest";
  }

  static const char* value(const ::laser_tag::TagActionObsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 0 - NORTH     \n"
"# 1 - EAST     \n"
"# 2 - SOUTH    \n"
"# 3 - WEST     \n"
"# 4 - TAG\n"
"\n"
"int32 action\n"
;
  }

  static const char* value(const ::laser_tag::TagActionObsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagActionObsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_tag::TagActionObsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_tag::TagActionObsRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_TAG_MESSAGE_TAGACTIONOBSREQUEST_H
