// Generated by gencpp from file laser_tag/YoubotActionObsRequest.msg
// DO NOT EDIT!


#ifndef LASER_TAG_MESSAGE_YOUBOTACTIONOBSREQUEST_H
#define LASER_TAG_MESSAGE_YOUBOTACTIONOBSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_tag
{
template <class ContainerAllocator>
struct YoubotActionObsRequest_
{
  typedef YoubotActionObsRequest_<ContainerAllocator> Type;

  YoubotActionObsRequest_()
    : direction()  {
    }
  YoubotActionObsRequest_(const ContainerAllocator& _alloc)
    : direction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct YoubotActionObsRequest_

typedef ::laser_tag::YoubotActionObsRequest_<std::allocator<void> > YoubotActionObsRequest;

typedef boost::shared_ptr< ::laser_tag::YoubotActionObsRequest > YoubotActionObsRequestPtr;
typedef boost::shared_ptr< ::laser_tag::YoubotActionObsRequest const> YoubotActionObsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator1> & lhs, const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator1> & lhs, const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laser_tag

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "326e9417def5db9a05a2704a4d8de15e";
  }

  static const char* value(const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x326e9417def5db9aULL;
  static const uint64_t static_value2 = 0x05a2704a4d8de15eULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_tag/YoubotActionObsRequest";
  }

  static const char* value(const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# directions \n"
"# North - NORTH     \n"
"# East  - EAST     \n"
"# South - SOUTH    \n"
"# West  - WEST     \n"
"# NE    - NORTHEAST\n"
"# SE    - SOUTHEAST\n"
"# SW    - SOUTHWEST\n"
"# NW    - NORTHWEST\n"
"\n"
"string direction\n"
;
  }

  static const char* value(const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoubotActionObsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_tag::YoubotActionObsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_tag::YoubotActionObsRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_TAG_MESSAGE_YOUBOTACTIONOBSREQUEST_H
