// Generated by gencpp from file laser_tag/YoubotActionObs.msg
// DO NOT EDIT!


#ifndef LASER_TAG_MESSAGE_YOUBOTACTIONOBS_H
#define LASER_TAG_MESSAGE_YOUBOTACTIONOBS_H

#include <ros/service_traits.h>


#include <laser_tag/YoubotActionObsRequest.h>
#include <laser_tag/YoubotActionObsResponse.h>


namespace laser_tag
{

struct YoubotActionObs
{

typedef YoubotActionObsRequest Request;
typedef YoubotActionObsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct YoubotActionObs
} // namespace laser_tag


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_tag::YoubotActionObs > {
  static const char* value()
  {
    return "a51480b466976e5076b2241b78665302";
  }

  static const char* value(const ::laser_tag::YoubotActionObs&) { return value(); }
};

template<>
struct DataType< ::laser_tag::YoubotActionObs > {
  static const char* value()
  {
    return "laser_tag/YoubotActionObs";
  }

  static const char* value(const ::laser_tag::YoubotActionObs&) { return value(); }
};


// service_traits::MD5Sum< ::laser_tag::YoubotActionObsRequest> should match
// service_traits::MD5Sum< ::laser_tag::YoubotActionObs >
template<>
struct MD5Sum< ::laser_tag::YoubotActionObsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_tag::YoubotActionObs >::value();
  }
  static const char* value(const ::laser_tag::YoubotActionObsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_tag::YoubotActionObsRequest> should match
// service_traits::DataType< ::laser_tag::YoubotActionObs >
template<>
struct DataType< ::laser_tag::YoubotActionObsRequest>
{
  static const char* value()
  {
    return DataType< ::laser_tag::YoubotActionObs >::value();
  }
  static const char* value(const ::laser_tag::YoubotActionObsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_tag::YoubotActionObsResponse> should match
// service_traits::MD5Sum< ::laser_tag::YoubotActionObs >
template<>
struct MD5Sum< ::laser_tag::YoubotActionObsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_tag::YoubotActionObs >::value();
  }
  static const char* value(const ::laser_tag::YoubotActionObsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_tag::YoubotActionObsResponse> should match
// service_traits::DataType< ::laser_tag::YoubotActionObs >
template<>
struct DataType< ::laser_tag::YoubotActionObsResponse>
{
  static const char* value()
  {
    return DataType< ::laser_tag::YoubotActionObs >::value();
  }
  static const char* value(const ::laser_tag::YoubotActionObsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_TAG_MESSAGE_YOUBOTACTIONOBS_H
